spring:
  application:
    name: gatewayservice
  redis:
    port: 6379
    host: localhost
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      loadbalancer:
        ribbon:
          enabled: true
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/v1/user-service/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
        - id: friendservice
          uri: lb://friendservice
          predicates:
            - Path=/api/v1/friend-service/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
        - id: chatservice
          uri: lb://chatservice
          predicates:
            - Path=/api/v1/chat-service/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
# Cau hinh JWT
jwt:
  secret: 6d9a269ae108eda9f5a28284e86f203d0a3e6ddffadc5a84784d57e99679df3a
  expirationtime: 900000
  expirationrefreshtime: 604800000