spring:
  application:
    name: commonservice

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}
      auto-offset-reset: earliest
    listener:
      concurrency: 3
  mail:
    host: smtp.gmail.com
    port: 587
    username: lockbkbang@gmail.com
    password: ohgx uhlo nbii rlle
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true